# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrape.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 587)
        MainWindow.setMinimumSize(QtCore.QSize(886, 587))
        MainWindow.setMaximumSize(QtCore.QSize(886, 587))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 891, 41))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color:rgba(7, 19, 35, 240);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(850, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"   color: white\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(810, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"   color: white\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 891, 551))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"background-color:rgba(16, 30, 41, 240);\n"
"}\n"
"\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setGeometry(QtCore.QRect(-160, 70, 1071, 491))
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"background-color:rgba(16, 30, 41, 240); \n"
"color:rgba(16, 30, 41, 240); \n"
" }\n"
"QTabBar{\n"
"background-color:rgba(16, 30, 41, 240);\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setStyleSheet("background-color:rgba(16, 30, 41, 240);\n"
"border:none")
        self.tab1.setObjectName("tab1")
        self.comboBox = QtWidgets.QComboBox(self.tab1)
        self.comboBox.setGeometry(QtCore.QRect(190, 70, 191, 22))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(190, 50, 71, 16))
        self.label_3.setStyleSheet("color:white\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(190, 110, 81, 16))
        self.label_4.setStyleSheet("color:white\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit.setGeometry(QtCore.QRect(190, 130, 191, 20))
        self.lineEdit.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.progressBar = QtWidgets.QProgressBar(self.tab1)
        self.progressBar.setGeometry(QtCore.QRect(420, 390, 611, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    text-align: center;\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"   color:white\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(950, 420, 71, 16))
        self.label_5.setStyleSheet("color:white\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(860, 420, 71, 16))
        self.label_6.setStyleSheet("color:white\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab1)
        self.tableWidget_3.setGeometry(QtCore.QRect(420, 30, 601, 351))
        self.tableWidget_3.setStyleSheet("QTableWidget {\n"
"\n"
"background-color:rgb(215, 215, 215);\n"
"color:black;\n"
"\n"
"\n"
"}")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 340, 191, 20))
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"background-color:rgb(215, 215, 215);\n"
"text: \"sadsad\"\n"
"}\n"
"QLineEdit:focus{\n"
" text:\"  \";\n"
"}\n"
"")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_22 = QtWidgets.QLabel(self.tab1)
        self.label_22.setGeometry(QtCore.QRect(190, 320, 81, 16))
        self.label_22.setStyleSheet("color:white\n"
"")
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setStyleSheet("background-color:rgba(16, 30, 41, 240);\n"
"border:none")
        self.tab2.setObjectName("tab2")
        self.label_7 = QtWidgets.QLabel(self.tab2)
        self.label_7.setGeometry(QtCore.QRect(190, 40, 81, 16))
        self.label_7.setStyleSheet("color:white\n"
"")
        self.label_7.setObjectName("label_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_10.setGeometry(QtCore.QRect(360, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 69, 161, 21))
        self.lineEdit_2.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 190, 191, 22))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_3.setGeometry(QtCore.QRect(190, 130, 191, 22))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.tab2)
        self.label_9.setGeometry(QtCore.QRect(190, 170, 81, 16))
        self.label_9.setStyleSheet("color:white\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.tab2)
        self.label_8.setGeometry(QtCore.QRect(190, 110, 71, 16))
        self.label_8.setStyleSheet("color:white\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.tab2)
        self.label_10.setGeometry(QtCore.QRect(190, 220, 81, 16))
        self.label_10.setStyleSheet("color:white\n"
"")
        self.label_10.setObjectName("label_10")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_4.setGeometry(QtCore.QRect(190, 240, 191, 22))
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_11.setGeometry(QtCore.QRect(340, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_11 = QtWidgets.QLabel(self.tab2)
        self.label_11.setGeometry(QtCore.QRect(250, 300, 71, 16))
        self.label_11.setStyleSheet("color:white\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_12.setGeometry(QtCore.QRect(340, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_12 = QtWidgets.QLabel(self.tab2)
        self.label_12.setGeometry(QtCore.QRect(190, 340, 101, 16))
        self.label_12.setStyleSheet("color:white\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab2)
        self.label_13.setGeometry(QtCore.QRect(460, 30, 41, 16))
        self.label_13.setStyleSheet("color:white\n"
"")
        self.label_13.setObjectName("label_13")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab2)
        self.tableWidget_4.setGeometry(QtCore.QRect(460, 60, 601, 351))
        self.tableWidget_4.setStyleSheet("QTableWidget {\n"
"\n"
"background-color:rgb(215, 215, 215);\n"
"color:black;\n"
"\n"
"\n"
"}")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(7)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab2)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 370, 141, 20))
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"background-color:rgb(215, 215, 215);\n"
"text: \"sadsad\"\n"
"}\n"
"QLineEdit:focus{\n"
" text:\"  \";\n"
"}\n"
"")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_23 = QtWidgets.QLabel(self.tab2)
        self.label_23.setGeometry(QtCore.QRect(190, 280, 61, 16))
        self.label_23.setStyleSheet("color:white\n"
"")
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color:rgba(16, 30, 41, 240);\n"
"border:none")
        self.tab.setObjectName("tab")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(460, 30, 41, 16))
        self.label_14.setStyleSheet("color:white\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(180, 30, 81, 16))
        self.label_15.setStyleSheet("color:white\n"
"")
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 59, 161, 21))
        self.lineEdit_3.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(350, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 120, 161, 20))
        self.lineEdit_4.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(180, 100, 61, 16))
        self.label_16.setStyleSheet("color:white\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(180, 150, 61, 16))
        self.label_17.setStyleSheet("color:white\n"
"")
        self.label_17.setObjectName("label_17")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 170, 161, 20))
        self.lineEdit_5.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(180, 200, 61, 16))
        self.label_18.setStyleSheet("color:white\n"
"")
        self.label_18.setObjectName("label_18")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 220, 161, 20))
        self.lineEdit_6.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(180, 300, 61, 16))
        self.label_19.setStyleSheet("color:white\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(180, 250, 71, 16))
        self.label_21.setStyleSheet("color:white\n"
"")
        self.label_21.setObjectName("label_21")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(320, 370, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(350, 120, 65, 21))
        self.comboBox_6.setMinimumSize(QtCore.QSize(62, 0))
        self.comboBox_6.setMaximumSize(QtCore.QSize(65, 60))
        self.comboBox_6.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 3em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_6.setIconSize(QtCore.QSize(15, 15))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_7.setGeometry(QtCore.QRect(350, 170, 65, 20))
        self.comboBox_7.setMinimumSize(QtCore.QSize(62, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(65, 65))
        self.comboBox_7.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 3em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_7.setIconSize(QtCore.QSize(15, 15))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_8.setGeometry(QtCore.QRect(350, 220, 65, 21))
        self.comboBox_8.setMinimumSize(QtCore.QSize(62, 0))
        self.comboBox_8.setMaximumSize(QtCore.QSize(65, 16777215))
        self.comboBox_8.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 3em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setIconSize(QtCore.QSize(15, 15))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab)
        self.comboBox_9.setGeometry(QtCore.QRect(350, 270, 65, 21))
        self.comboBox_9.setMinimumSize(QtCore.QSize(62, 0))
        self.comboBox_9.setMaximumSize(QtCore.QSize(65, 16777215))
        self.comboBox_9.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 3em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.comboBox_9.setEditable(True)
        self.comboBox_9.setIconSize(QtCore.QSize(15, 15))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_5.setGeometry(QtCore.QRect(460, 60, 601, 351))
        self.tableWidget_5.setStyleSheet("QTableWidget {\n"
"\n"
"background-color:rgb(215, 215, 215);\n"
"color:black;\n"
"\n"
"\n"
"}")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(7)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(430, 120, 21, 21))
        self.checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(430, 170, 21, 21))
        self.checkBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(430, 220, 21, 21))
        self.checkBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(430, 270, 21, 21))
        self.checkBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 320, 161, 20))
        self.lineEdit_9.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(180, 270, 161, 20))
        self.lineEdit_10.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color:rgba(16, 30, 41, 240);\n"
"border:none")
        self.tab_2.setObjectName("tab_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(320, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(450, 61, 601, 351))
        self.tableWidget_6.setStyleSheet("QTableWidget {\n"
"\n"
"background-color:rgb(215, 215, 215);\n"
"color:black;\n"
"\n"
"\n"
"}")
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(7)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(340, 61, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(450, 31, 41, 16))
        self.label_20.setStyleSheet("color:white\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(170, 100, 71, 16))
        self.label_24.setStyleSheet("color:white\n"
"")
        self.label_24.setObjectName("label_24")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(170, 130, 161, 20))
        self.lineEdit_11.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(170, 31, 81, 16))
        self.label_25.setStyleSheet("color:white\n"
"")
        self.label_25.setObjectName("label_25")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 60, 161, 21))
        self.lineEdit_12.setStyleSheet("background-color:rgb(215, 215, 215)\n"
"")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(330, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(170, 350, 101, 16))
        self.label_26.setStyleSheet("color:white\n"
"")
        self.label_26.setObjectName("label_26")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(170, 380, 141, 20))
        self.lineEdit_13.setStyleSheet("QLineEdit{\n"
"background-color:rgb(215, 215, 215);\n"
"text: \"sadsad\"\n"
"}\n"
"QLineEdit:focus{\n"
" text:\"  \";\n"
"}\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(250, 230, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 891, 101))
        self.widget.setObjectName("widget")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(0,125,236,255);\n"
"border-radius:10px;\n"
"background-color:rgb(16, 29, 41)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background-color:rgb(17, 30, 42);\n"
"    border: none;\n"
"   color: white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,125,236,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: white;\n"
"   color : black\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 891, 20))
        self.frame_3.setStyleSheet("background-color:rgba(16, 30, 41, 240);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "<strong>Scraping</strong> Window"))
        self.label_3.setText(_translate("MainWindow", "Select Contry"))
        self.label_4.setText(_translate("MainWindow", "Profiles Amount"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Profile Amount"))
        self.pushButton_6.setText(_translate("MainWindow", "Start"))
        self.pushButton_7.setText(_translate("MainWindow", "Pause"))
        self.pushButton_8.setText(_translate("MainWindow", "Stop"))
        self.pushButton_9.setText(_translate("MainWindow", "Export"))
        self.label_5.setText(_translate("MainWindow", "5692 Done"))
        self.label_6.setText(_translate("MainWindow", "6m 53s"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Connections"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Job Designation"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Enter Exported CSV file Name"))
        self.label_22.setText(_translate("MainWindow", "Enter Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.label_7.setText(_translate("MainWindow", "Import CSV File:"))
        self.pushButton_10.setText(_translate("MainWindow", "Import"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Imported File"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Insertion"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Quick"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Bubble"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Selection"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Merge"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "TimSort"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Shell"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "CocktailSort"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "CombSort"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Full Name"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Username"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Company"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "No. of connections"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Country"))
        self.label_9.setText(_translate("MainWindow", "Select Algorithm"))
        self.label_8.setText(_translate("MainWindow", "Select Column"))
        self.label_10.setText(_translate("MainWindow", "Select Order"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Ascending"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Decending"))
        self.pushButton_11.setText(_translate("MainWindow", "Sort"))
        self.label_11.setText(_translate("MainWindow", "0.2 Seconds"))
        self.pushButton_12.setText(_translate("MainWindow", "Export"))
        self.label_12.setText(_translate("MainWindow", "Export Sorted Data"))
        self.label_13.setText(_translate("MainWindow", "Table:"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Connections"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Job Designation"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Enter Exported CSV file Name"))
        self.label_23.setText(_translate("MainWindow", "Time Taken:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.label_14.setText(_translate("MainWindow", "Table:"))
        self.label_15.setText(_translate("MainWindow", "Import CSV File:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Imported File"))
        self.pushButton_13.setText(_translate("MainWindow", "Import"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "e.g Nouman Tariq"))
        self.label_16.setText(_translate("MainWindow", "Type Name:"))
        self.label_17.setText(_translate("MainWindow", "Username"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "@Nouman0x45"))
        self.label_18.setText(_translate("MainWindow", "Company"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "UET Lahore"))
        self.label_19.setText(_translate("MainWindow", "Connections"))
        self.label_21.setText(_translate("MainWindow", "Select Contry"))
        self.pushButton_14.setText(_translate("MainWindow", "Search"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "AND"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "OR"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "AND"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "OR"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "AND"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "OR"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "AND"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "OR"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Connections"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Job Designation"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "From 0 to Any Number"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Select Country"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.pushButton_15.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Connections"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Job Designation"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        self.pushButton_16.setText(_translate("MainWindow", "Import"))
        self.label_20.setText(_translate("MainWindow", "Table:"))
        self.label_24.setText(_translate("MainWindow", "Type Search:"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Any Entity"))
        self.label_25.setText(_translate("MainWindow", "Import CSV File:"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Imported File"))
        self.pushButton_17.setText(_translate("MainWindow", "Export"))
        self.label_26.setText(_translate("MainWindow", "Export Sorted Data"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "Enter Exported CSV file Name"))
        self.pushButton_18.setText(_translate("MainWindow", "Advanced Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.pushButton_5.setText(_translate("MainWindow", "Sort"))
        self.pushButton_4.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "<strong>LinkedIn</strong> Scraper"))
        self.pushButton_3.setText(_translate("MainWindow", "Scrape"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
